-- Drop tables
DROP TABLE IF EXISTS Product_Category;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Product_Similars;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS DVD_Person;
DROP TABLE IF EXISTS CD_Person;
DROP TABLE IF EXISTS Book_Person;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Purchase;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Offer;
DROP TABLE IF EXISTS Title;
DROP TABLE IF EXISTS DVD;
DROP TABLE IF EXISTS CD;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Shop;

